language: python

python:
- '3.5'
- '3.6'
- '3.7'

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install -r ./doc/requirements.txt

script:
- flake8
- coverage run -m pytest
- coverage html -d htmlcov
- coverage report --fail-under=35
- python setup.py install
- ./scripts/documentation/build_all

after_success:
  - bash <(curl -s https://codecov.io/bash)